name: poop_journal
description: Poop Journal
version: 2.0.0+2
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter:

dependencies:
  bloc: ^8.1.4
  firebase_analytics: ^10.8.0
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.17.9
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.19
  firebase_in_app_messaging: ^0.7.4+15
  firebase_performance: ^0.9.3+15
  firebase_remote_config: ^4.3.18
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  intl:
#  flutter_gen: ^5.6.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis:

flutter:
  uses-material-design: true
  generate: true

#name: poop_journal
#description: Poop Journal
#version: 1.0.0+1
#publish_to: none
#
#environment:
#  sdk: ">=2.18.0 <3.0.0"
#  flutter: 3.3.8
#
#dependencies:
#  bloc: ^8.1.4
#  firebase_analytics: ^11.1.0
#  firebase_app_check: ^0.3.0+2
#  firebase_auth: ^5.1.1
#  firebase_core: ^3.1.1
#  firebase_crashlytics: ^4.0.2
#  firebase_in_app_messaging: ^0.8.0+2
#  firebase_performance: ^0.10.0+2
#  firebase_remote_config: ^5.0.2
#  flutter:
#    sdk: flutter
#  flutter_bloc: ^8.1.5
#  flutter_localizations:
#    sdk: flutter
#  intl: ^0.19.0
#
#  flutter_gen: any
#dev_dependencies:
#  bloc_test: ^9.1.7
#  flutter_test:
#    sdk: flutter
#  mocktail: ^1.0.0
#  very_good_analysis: ^6.0.0
#
#  app: any
#flutter:
#  uses-material-design: true
#  generate: true
