// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSXRUHI1_oG4dfiE75dkHs5HCJOWC1sM',
    appId: '1:570344895287:web:d19ca81e87c1e4091860b2',
    messagingSenderId: '570344895287',
    projectId: 'poop-journal',
    authDomain: 'poop-journal.firebaseapp.com',
    storageBucket: 'poop-journal.appspot.com',
    measurementId: 'G-16XGXJHH2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgq1S0y8okio97iLLYKQSk6Y2W3dwMTcE',
    appId: '1:570344895287:android:8963656919380f021860b2',
    messagingSenderId: '570344895287',
    projectId: 'poop-journal',
    storageBucket: 'poop-journal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5ZedZ-_kvD3ZfmeKhAfUM8Sm_OJAvbw',
    appId: '1:570344895287:ios:f870ccc5d1b67b371860b2',
    messagingSenderId: '570344895287',
    projectId: 'poop-journal',
    storageBucket: 'poop-journal.appspot.com',
    iosBundleId: 'rocks.poopjournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5ZedZ-_kvD3ZfmeKhAfUM8Sm_OJAvbw',
    appId: '1:570344895287:ios:f870ccc5d1b67b371860b2',
    messagingSenderId: '570344895287',
    projectId: 'poop-journal',
    storageBucket: 'poop-journal.appspot.com',
    iosBundleId: 'rocks.poopjournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATSXRUHI1_oG4dfiE75dkHs5HCJOWC1sM',
    appId: '1:570344895287:web:1fc78e9787d0b20a1860b2',
    messagingSenderId: '570344895287',
    projectId: 'poop-journal',
    authDomain: 'poop-journal.firebaseapp.com',
    storageBucket: 'poop-journal.appspot.com',
    measurementId: 'G-TRJESCEK7D',
  );

}